version: "3.8"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    container_name: mongodb

  transaction-api:
    build: .
    ports:
      - "8080:8080"
    container_name: transaction-api
    environment:
      - COLL_NAME=testCollection
      - DB_NAME=transactionsData
      - MONGO_URI=mongodb://mongodb:27017
      - ADDRESS=0.0.0.0
      - PORT=8080
