version: '3.8'
services:
  
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    container_name: mongodb

  transaction-api:
    build: .
    ports:
      - "8080:8080"
    container_name: transaction-api
    environment:
      - collName=testCollection
      - dBName=transactionsData
      - uri=mongodb://mongodb:27017
      - address=0.0.0.0
      - port=8080