name: Publish Docker image

on: push

jobs:
  push_to_registry:
    name: Push Docker image to GitHub
    runs-on: ubuntu-latest
    steps: 

#      - name: Super-Linter
#        uses: super-linter/super-linter@v5.1.1

      - name: Checkout code
        uses: actions/checkout@v2
        
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
