name: Publish Docker image

on: push

jobs:
  push_to_registry:
    name: Push Docker image to GitHub
    runs-on: ubuntu-latest
    steps: 
      - name: Check out code
        uses: actions/checkout@3
        
      - name: Log in to GitHub
