#name: Publish

#on: push

#jobs:
#  test-job:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v3

#    - name: Install dependencies
#      run: npm ci

#    - name: Test
#      run: npm test

